const GridItems = [
  {
    layout: '2x2',
    type: 'social',
    title: 'LinkedIn',
    icon: 'linkedin',
    username: 'dheeraj-rs',
    description:
      'Connect with me on LinkedIn to explore my professional journey and stay updated on my latest achievements and projects showcased in my portfolio website.',
    color: '#0077b5',
    buttonTitle: 'Connect With me!',
    buttonLink: 'https://github.com/dheeraj-rs',
  },

  {
    layout: '2x2',
    type: 'social',
    title: 'Github',
    icon: 'github',
    username: '@dheeraj-rs',
    buttonTitle: 'Follow Me!',
    buttonSecondaryText: '',
    buttonLink: 'https://github.com/dheeraj-rs',
    color: '#070707',
    description: 'Click on me to view my open-source projects!',
  },
  {
    layout: '1x2',
    type: 'social',
    title: 'Twitter',
    icon: 'twitter',
    username: '@dheeraj_rs_',
    buttonTitle: 'Follow',
    buttonLink: 'https://github.com/dheeraj-rs',
    buttonSecondaryText: '193',
    color: '#1DA1F2',
    description: 'Software Engineer building in Public!',
  },
  {
    layout: '1x2',
    type: 'social',
    title: 'Resume',
    icon: 'resume',
    username: '',
    buttonTitle: 'Download',
    buttonLink: '',
    buttonSecondaryText: '',
    color: '#070707',
    description: 'Download My resume!',
  },

  {
    layout: '2x2',
    type: 'social',
    title: 'Calendly',
    icon: 'calendly',
    username: '',
    description: 'Book a 30 min Call with me',
    color: '#070707',
    buttonTitle: 'Schedule',
    buttonLink: 'https://github.com/dheeraj-rs',
  },
  {
    layout: '2x1',
    type: 'project',
    // title: 'Sign in with Ethereum',
    title: 'GET START',
    icon: 'pi pi-external-link',
    color: '#070707',
    buttonLink: '/',
    stars: 1,
  },
  {
    layout: '2x1',
    type: 'project',
    title: 'NestJS JWT Auth template',
    icon: 'github',
    color: '#070707',
    stars: 2,

    buttonLink: 'https://github.com/dheeraj-rs',
  },
];

const GridItemsLower = [
  ,
  {
    layout: '1x2',
    type: 'social',
    title: 'InfinityTools',
    username: '',
    description: 'A collection of AI tools',
    icon: 'next',
    buttonTitle: 'Coming Soon!',
    buttonSecondaryText: '',
    buttonLink: '/',
  },

  {
    layout: '2x2',
    type: 'social',
    title: 'Restaurant Web3 Membership System NFT ',
    username: 'Le Vesuvio',
    description:
      'NFT collection and membership website made for Le Vesuvio restaurant.',
    icon: 'next',
    buttonTitle: 'View Project',
    buttonSecondaryText: '',
    buttonLink: 'https://github.com/dheeraj-rs',
  },
  {
    layout: '1x2',
    type: 'social',
    title: 'AI Agency',
    username: '',
    description: 'Generate Ai employees that you can Chat with!',
    icon: 'next',
    buttonTitle: 'Coming Soon!',
    buttonSecondaryText: '',
    buttonLink: '/',
  },
  {
    layout: '2x1',
    type: 'project',
    title: 'KnowledgeBase Chat AI Saas ',
    icon: 'github',
    stars: 1,
    color: '#070707',
    buttonLink: 'https://github.com/dheeraj-rs',
  },
  {
    layout: '2x2',
    type: 'social',
    title: 'AktionT4 NFT Collection & Backend',
    username: '',
    description: 'Aktion T4 Blockchain and Backend Development',
    icon: 'ethereum',
    buttonTitle: 'View Project',
    buttonSecondaryText: '',
    buttonLink: 'https://github.com/dheeraj-rs',
  },
  ,
  {
    layout: '1x2',
    type: 'social',
    title: 'NFT GAME 1024',
    username: '',
    description:
      'Smart Contract and Website development of 1024 Blockchain Game',
    icon: 'ethereum',
    buttonTitle: 'View Project',
    buttonSecondaryText: '',
    buttonLink: '1024-landingpage-tan.vercel.app',
  },
  {
    layout: '1x2',
    type: 'social',
    title: 'Priority Queue Management System',
    username: 'QueueUp',
    description: 'Priority Queue management system built with django',
    icon: 'django',
    buttonTitle: 'View Project',
    buttonSecondaryText: '',
    buttonLink: 'https://github.com/dheeraj-rs',
  },
  {
    layout: '2x1',
    type: 'project',
    title: 'Portfolio Website Source Code',
    icon: 'github',
    stars: 1,
    color: '#070707',
    buttonLink: 'https://github.com/dheeraj-rs',
  },
];

export const siteConfig = {
  creator: 'DHEERAJ',
  title: 'Software Developer ',
  bio: 'Software Developer',
  location: 'Calicut',
  locationLink: '',
  email: 'drjsde@gmail.com',
  items: GridItems,
  itemsLower: GridItemsLower,
};
